// <auto-generated />
using System;
using ExamenParcial2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Examen2.Migrations
{
    [DbContext(typeof(TiendaContext))]
    partial class TiendaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ExamenParcial2.Models.Autor", b =>
                {
                    b.Property<int>("id_Autor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("Edad")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<string>("Nacionalidad")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("librosid_Autor")
                        .HasColumnType("int");

                    b.HasKey("id_Autor");

                    b.HasIndex("librosid_Autor");

                    b.ToTable("Autor");
                });

            modelBuilder.Entity("ExamenParcial2.Models.libros", b =>
                {
                    b.Property<int>("id_Autor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Titulo")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("isbn")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("precio")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.HasKey("id_Autor");

                    b.ToTable("libros");
                });

            modelBuilder.Entity("ExamenParcial2.Models.Autor", b =>
                {
                    b.HasOne("ExamenParcial2.Models.libros", null)
                        .WithMany("Autores")
                        .HasForeignKey("librosid_Autor");
                });

            modelBuilder.Entity("ExamenParcial2.Models.libros", b =>
                {
                    b.Navigation("Autores");
                });
#pragma warning restore 612, 618
        }
    }
}
